### ISSUE TITLE
url to add

### ISSUE THREAD

**Issue by robmarkcole** [ermongroup/TEOChat#1]
https://arxiv.org/abs/2410.06234

**Comment by jirvin16** [comment]
Hi @robmarkcole, thanks so much for your interest in our work! Did you have a request or did you mean to post this as an issue in a different repository?

**Comment by robmarkcole** [comment]
Suggesting adding the link to the paper as a convenience

**Comment by jirvin16** [comment]
Ah got it, thanks. Just added the link to the News section of the README, and the paper can also be accessed by clicking the title in the README or the arXiv badge.
