### ISSUE TITLE
请问如何使用lora微调teochat？

### ISSUE THREAD

**Issue by BrooksXiaoxi** [ermongroup/TEOChat#2]
请问是否能够出一个包含微调数据集格式的lora微调教程？十分期待您能够回复

**Comment by jirvin16** [comment]
My understanding is that you are stating:
> Could you please provide a tutorial on LoRa fine-tuning that includes the format of the fine-tuning dataset? I am very much looking forward to your reply.

We will be making the data public and providing directions for LoRA fine-tuning soon.

Trying my best to translate:
我们很快会公开数据并提供LoRA微调的指导。

**Comment by BrooksXiaoxi** [comment]
哈哈是的，您的翻译十分准确。TEOchat十分优秀，我很期待您未来提供的教程，感谢您的回复！
Your translation is spot on! TEOchat is fantastic, and I’m really looking forward to the tutorials you’ll provide in the future. Thanks for your reply.

**Comment by BrooksXiaoxi** [comment]
> My understanding is that you are stating:
> 
> > Could you please provide a tutorial on LoRa fine-tuning that includes the format of the fine-tuning dataset? I am very much looking forward to your reply.
> 
> We will be making the data public and providing directions for LoRA fine-tuning soon.
> 
> Trying my best to translate: 我们很快会公开数据并提供LoRA微调的指导。

哈哈是的，您的翻译十分准确。TEOchat十分优秀，我很期待您未来提供的教程，感谢您的回复！
Your translation is spot on! TEOchat is fantastic, and I’m really looking forward to the tutorials you’ll provide in the future. Thanks for your reply.
